<a href="https://colab.research.google.com/github/Nitishagyawali/workshop1-of-AI/blob/main/woekshope01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Please complete all the problem listed below.
4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
Code / Implementation:

In [ ]:
import numpy as np


empty_array = np.empty((2, 2))

ones_array = np.ones((4, 2))


filled_array = np.full((3, 3), 7)

given_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(given_array)

ones_like_array = np.ones_like(given_array)

new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)

# Output the results for verification.
print("1. Empty Array (2x2):\n", empty_array)
print("\n2. All-One Array (4x2):\n", ones_array)
print("\n3. Filled Array (3x3, fill_value=7):\n", filled_array)
print("\n4. Zeros Like Array:\n", zeros_like_array)
print("\n5. Ones Like Array:\n", ones_like_array)
print("\n6. List to NumPy Array:\n", numpy_array)


1. Empty Array (2x2):
 [[0. 0.]
 [0. 0.]]

2. All-One Array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Filled Array (3x3, fill_value=7):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros Like Array:
 [[0 0]
 [0 0]]

5. Ones Like Array:
 [[1 1]
 [1 1]]

6. List to NumPy Array:
 [1 2 3 4]


Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.






In [ ]:
import numpy as np


array_10_to_49 = np.arange(10, 50)


matrix_0_to_8 = np.arange(9).reshape(3, 3)


identity_matrix = np.eye(3)


random_array = np.random.random(30)
mean_value = random_array.mean()


random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()


zero_array = np.zeros(10)
zero_array[4] = 1


arr = np.array([1, 2, 0, 0, 4, 0])
reversed_array = arr[::-1]


border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0


checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1


print("1. Array 10 to 49:\n", array_10_to_49)
print("\n2. 3x3 Matrix 0 to 8:\n", matrix_0_to_8)
print("\n3. Identity Matrix:\n", identity_matrix)
print("\n4. Random Array Mean:\n", mean_value)
print("\n5. Random 10x10 Array Min & Max:\nMin:", min_value, "Max:", max_value)
print("\n6. Zero Array with 5th Element as 1:\n", zero_array)
print("\n7. Reversed Array:\n", reversed_array)
print("\n8. 2D Array with Border 1 and Inside 0:\n", border_array)
print("\n9. 8x8 Checkerboard Pattern:\n", checkerboard)


1. Array 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 Matrix 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random Array Mean:
 0.5679559849036404

5. Random 10x10 Array Min & Max:
Min: 0.0070698787142777775 Max: 0.9940818361634236

6. Zero Array with 5th Element as 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reversed Array:
 [0 4 0 0 2 1]

8. 2D Array with Border 1 and Inside 0:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

9. 8x8 Checkerboard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np


x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])


add_xy = x + y


subtract_xy = x - y


multiply_x = x * 2

square_x = np.square(x)

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)


concat_xy_rows = np.concatenate((x, y), axis=0)
concat_vw_columns = np.vstack((v, w))


try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    concat_xv_error = str(e)

print("1. Add x and y:\n", add_xy)
print("\n2. Subtract x and y:\n", subtract_xy)
print("\n3. Multiply x by 2:\n", multiply_x)
print("\n4. Square of elements in x:\n", square_x)
print("\n5. Dot products:")
print("   Dot product of v and w:", dot_vw)
print("   Dot product of x and v:\n", dot_xv)
print("   Dot product of x and y:\n", dot_xy)
print("\n6. Concatenate x and y along rows:\n", concat_xy_rows)
print("\n   Concatenate v and w along columns:\n", concat_vw_columns)
print("\n7. Attempt to concatenate x and v:\n")
if 'concat_xv_error' in locals():
    print("   Error:", concat_xv_error)
else:
    print(concat_xv)


1. Add x and y:
 [[ 6  8]
 [10 13]]

2. Subtract x and y:
 [[-4 -4]
 [-4 -3]]

3. Multiply x by 2:
 [[ 2  4]
 [ 6 10]]

4. Square of elements in x:
 [[ 1  4]
 [ 9 25]]

5. Dot products:
   Dot product of v and w: 219
   Dot product of x and v:
 [29 77]
   Dot product of x and y:
 [[19 22]
 [50 58]]

6. Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

   Concatenate v and w along columns:
 [[ 9 10]
 [11 12]]

7. Attempt to concatenate x and v:

   Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Error while concatenating x and v: all the input arrays must have same number of
dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has
1 dimension(s)
Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.

3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for:
AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about
”linalg” function
of Numpy}
Code/Implementation:

In [ ]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

A_inv = np.linalg.inv(A)
I = np.eye(2)
result = np.dot(A, A_inv)
is_identity = np.allclose(result, I)
print("Is it identity ?  &quot;,is_identity")

AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB:")
print(AB)

print("\nBA:&quot")
print(BA)

is_equal = np.allclose(AB, BA)
print("\nIs AB equal to BA?&quot;, is_equal")

AB_T = np.transpose(np.dot(A, B))
BT_AT = np.dot(np.transpose(B), np.transpose(A))

print("Transpose of AB:")
print(AB_T)

print("\nBT * AT:")
print(BT_AT)
is_equal = np.allclose(AB_T, BT_AT)
print("\nIs (AB)^T equal to B^T * A^T?", is_equal)

A_matrix = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_matrix = np.array([-1, -3, 9])

X = np.linalg.inv(A_matrix).dot(B_matrix)
x, y, z = X

print("Value of x is: {x}")
print("Value of y is: {y}")
print("Value of z is: {z}")

import numpy as np

A_matrix = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_matrix = np.array([-1, -3, 9])

X = np.linalg.solve(A_matrix, B_matrix)

x, y, z = X

print("Value of x is: {x}")
print("Value of y is: {y}")
print("Value of z is: {z}")

Is it identity ?  &quot;,is_identity
AB:
[[23 13]
 [51 29]]

BA:&quot
[[36 44]
 [13 16]]

Is AB equal to BA?&quot;, is_equal
Transpose of AB:
[[23 51]
 [13 29]]

BT * AT:
[[23 51]
 [13 29]]

Is (AB)^T equal to B^T * A^T? True
Value of x is: {x}
Value of y is: {y}
Value of z is: {z}
Value of x is: {x}
Value of y is: {y}
Value of z is: {z}
